### ISSUE TITLE
[3주차/1] 2.3 스프링 부트 애플리케이션 시작 시 코드 실행

### ISSUE THREAD

**Issue by HwanGonJang** [gdsc-ssu/2024-spring-of-gdsc#7]
#### 나세빈
@sebbbin 
#### 날짜
- 2024-04-01
#### 진도
- 2.3 스프링 부트 애플리케이션 시작 시 코드 실행
#### 기타 자료
- 아무거나 필요한거

**Comment by HI-JIN2** [comment]
마크다운 적용이 안된 것 같아요~.
